site_name: SciencePedia
site_url: https://liaoruoxue.github.io/sciencepedia/
repo_url: https://github.com/liaoruoxue/sciencepedia
repo_name: SciencePedia

docs_dir: .

theme:
  name: material
  language: zh
  features:
    - navigation.instant # 页面无刷新跳转
    - navigation.tabs    # 顶部导航栏模式（适合分类多的情况）
    - navigation.top     # 返回顶部按钮
    - search.suggest
    - search.highlight
  palette: 
    - scheme: default
      primary: indigo 
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


# 开启 PWA 支持（手机上像 App 一样）
extra:
  manifest: manifest.webmanifest

# 插件配置
plugins:
  - search # 开启搜索
  - offline # 开启离线访问能力

# 排除不需要显示在电子书里的系统文件
exclude_docs: |
  .github/
  .gitignore
  mkdocs.yml
  requirements.txt
  LICENSE
  *.pdf

